version: "3.8"
services:
  omnibot:
    build: .
    env_file: docker.env
    volumes:
      - "./mix.exs:/app/mix.exs"
      - "./lib:/app/lib"
      - "./config:/app/config"
      - "./data:/app/data"
      - "./omnibot.exs:/app/omnibot.exs"
    working_dir: "/app"
    restart: always
